{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "enricher age duration rate",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(enricher_request_duration_seconds_bucket{type=\"age\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "enricher gender duration rate",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(enricher_request_duration_seconds_bucket{type=\"gender\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "enricher age duration rate",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(enricher_request_duration_seconds_bucket{type=\"nationality\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http duration GET /v1/people",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{method=\"GET\", path=\"/v1/people\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http duration GET /v1/people{id}",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{method=\"GET\", path=\"/v1/people/{id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http duration PUT /v1/people{id}",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{method=\"PUT\", path=\"/v1/people/{id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http duration POST /v1/people{id}",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{method=\"POST\", path=\"/v1/people\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "service duration CreatePerson",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "service_method_duration_seconds_bucket{method=\"CreatePerson\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "service duration GetPeople",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "service_method_duration_seconds_bucket{method=\"GetPeople\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "service duration GetPersonById",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "service_method_duration_seconds_bucket{method=\"UpdatePerson\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "service duration GetPersonById",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "service_method_duration_seconds_bucket{method=\"GetPersonByID\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}